PATCH {{BASE_URL}}:{{PORT}}/api/events/3
Content-Type: application/json

{
  "name": "Event 3 Updated",
  "description": "Updated description of event 3",
  "location": "Updated location of event 3",
  "dateTime": "2024-01-01T15:30:00Z"
}

